/**
 * AI Content page - displays all AI-generated and processed content
 */

import { baseLayout } from '../layouts/base';
import { nav } from '../components/nav';
import { pageHeader } from '../components/page-header';
import { emptyState } from '../components/empty-state';

export interface AIContentPageProps {
  count: number;
  apiBase: string;
}

export function aiContentPage({ count, apiBase }: AIContentPageProps): string {
  const content = `
    ${nav({ currentPage: '/dashboard/ai-content', apiBase })}

    <div class="container">
      ${pageHeader({
        title: 'AI Generated Content',
        subtitle: 'Content processed and generated by AI',
        icon: '✨',
        count,
        backLink: '/dashboard'
      })}

      <!-- Search and Filter -->
      <div class="toolbar">
        <div class="search-box">
          <input type="text" id="search-input" placeholder="Search content..." />
          <span class="search-icon">🔍</span>
        </div>
        <div class="toolbar-actions">
          <select id="mode-filter">
            <option value="">All Types</option>
            <option value="rewrite_twitter">Twitter Rewrite</option>
            <option value="rewrite_linkedin">LinkedIn Post</option>
            <option value="describe_image">Image Description</option>
            <option value="summarize">Summary</option>
            <option value="translate">Translation</option>
          </select>
          <select id="sort-select">
            <option value="newest">Newest first</option>
            <option value="oldest">Oldest first</option>
          </select>
        </div>
      </div>

      <!-- Content List -->
      <div id="content-container">
        ${count === 0 ? emptyState({
          title: 'No AI Content Yet',
          message: 'Use the extension to process text with AI. Rewrite for Twitter, describe images, translate, and more.',
          icon: '✨',
          actionText: 'Learn More',
          actionUrl: '/setup'
        }) : '<div class="loading-container"><div class="loading"></div></div>'}
      </div>

      <!-- Pagination -->
      <div id="pagination" class="pagination"></div>
    </div>
  `;

  const styles = `
    <style>
      .toolbar {
        display: flex;
        gap: 1rem;
        margin-bottom: 1.5rem;
        flex-wrap: wrap;
      }

      .search-box {
        position: relative;
        flex: 1;
        min-width: 200px;
      }

      .search-box input {
        width: 100%;
        padding: 0.75rem 1rem 0.75rem 2.5rem;
        border: 1px solid var(--border);
        border-radius: 8px;
        font-size: 0.95rem;
        background: var(--surface);
      }

      .search-box input:focus {
        outline: none;
        border-color: var(--primary);
        box-shadow: 0 0 0 3px var(--primary-light);
      }

      .search-icon {
        position: absolute;
        left: 0.75rem;
        top: 50%;
        transform: translateY(-50%);
        font-size: 1rem;
      }

      .toolbar-actions {
        display: flex;
        gap: 0.75rem;
      }

      .toolbar-actions select {
        padding: 0.75rem 1rem;
        border: 1px solid var(--border);
        border-radius: 8px;
        background: var(--surface);
        font-size: 0.875rem;
        cursor: pointer;
      }

      .loading-container {
        display: flex;
        justify-content: center;
        padding: 3rem;
      }

      .content-grid {
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
      }

      .content-card {
        background: var(--surface);
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        border-left: 4px solid #10b981;
      }

      .content-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem 1.25rem;
        background: var(--background);
        border-bottom: 1px solid var(--border);
      }

      .content-type {
        display: flex;
        align-items: center;
        gap: 0.5rem;
      }

      .type-badge {
        background: var(--primary-light);
        color: var(--primary);
        font-size: 0.75rem;
        font-weight: 600;
        padding: 0.25rem 0.75rem;
        border-radius: 99px;
        text-transform: uppercase;
      }

      .content-date {
        font-size: 0.8rem;
        color: var(--text-secondary);
      }

      .content-body {
        padding: 1.25rem;
      }

      .content-section {
        margin-bottom: 1rem;
      }

      .content-section:last-child {
        margin-bottom: 0;
      }

      .content-label {
        font-size: 0.75rem;
        font-weight: 600;
        color: var(--text-secondary);
        text-transform: uppercase;
        margin-bottom: 0.5rem;
        display: flex;
        align-items: center;
        gap: 0.5rem;
      }

      .content-text {
        font-size: 0.95rem;
        color: var(--text-primary);
        line-height: 1.6;
        white-space: pre-wrap;
        word-break: break-word;
        background: var(--background);
        padding: 0.75rem 1rem;
        border-radius: 8px;
        max-height: 200px;
        overflow-y: auto;
      }

      .content-generated {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.05), rgba(16, 185, 129, 0.1));
        border: 1px solid rgba(16, 185, 129, 0.2);
      }

      .content-meta {
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
        font-size: 0.8rem;
        color: var(--text-secondary);
        padding-top: 1rem;
        margin-top: 1rem;
        border-top: 1px solid var(--border);
      }

      .content-meta-item {
        display: flex;
        align-items: center;
        gap: 0.35rem;
      }

      .copy-btn {
        background: var(--primary);
        color: white;
        border: none;
        padding: 0.5rem 1rem;
        border-radius: 6px;
        font-size: 0.8rem;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s;
        display: inline-flex;
        align-items: center;
        gap: 0.35rem;
      }

      .copy-btn:hover {
        background: var(--primary-dark);
      }

      .copy-btn.copied {
        background: var(--success);
      }

      .pagination {
        display: flex;
        justify-content: center;
        gap: 0.5rem;
        margin-top: 2rem;
      }

      .pagination button {
        padding: 0.5rem 1rem;
        border: 1px solid var(--border);
        border-radius: 6px;
        background: var(--surface);
        color: var(--text-primary);
        font-size: 0.875rem;
        cursor: pointer;
        transition: all 0.2s;
      }

      .pagination button:hover:not(:disabled) {
        background: var(--primary-light);
        border-color: var(--primary);
      }

      .pagination button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .pagination button.active {
        background: var(--primary);
        color: white;
        border-color: var(--primary);
      }

      .no-results {
        text-align: center;
        padding: 3rem;
        color: var(--text-secondary);
      }
    </style>
  `;

  const scripts = `
    <script>
      const API_BASE = '${apiBase}';
      let currentPage = 1;
      let currentSearch = '';
      let currentMode = '';
      let currentSort = 'newest';
      const perPage = 15;

      async function loadContent() {
        const container = document.getElementById('content-container');
        container.innerHTML = '<div class="loading-container"><div class="loading"></div></div>';

        try {
          const offset = (currentPage - 1) * perPage;
          let url = API_BASE + '/api/search/recent?table=posts&limit=100';

          if (currentSearch) {
            url += '&q=' + encodeURIComponent(currentSearch);
          }

          const response = await fetch(url);
          const data = await response.json();

          if (data.success && data.results) {
            // Filter only items with generated_output
            let content = data.results.filter(item => item.generated_output);

            // Filter by mode if selected
            if (currentMode) {
              content = content.filter(item => item.mode === currentMode);
            }

            // Sort
            if (currentSort === 'oldest') {
              content = content.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
            } else {
              content = content.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
            }

            // Paginate
            const total = content.length;
            const paginated = content.slice(offset, offset + perPage);

            if (paginated.length > 0) {
              const html = paginated.map((item, index) => {
                const date = new Date(item.created_at);
                const dateStr = date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
                const mode = item.mode || item.type || 'processed';
                const modeLabel = formatMode(mode);
                const uniqueId = 'content-' + index + '-' + Date.now();

                return \`
                  <div class="content-card">
                    <div class="content-header">
                      <div class="content-type">
                        <span class="type-badge">\${modeLabel}</span>
                      </div>
                      <span class="content-date">📅 \${dateStr}</span>
                    </div>
                    <div class="content-body">
                      <div class="content-section">
                        <div class="content-label">📝 Original Input</div>
                        <div class="content-text">\${escapeHtml(item.original_text || 'N/A')}</div>
                      </div>
                      <div class="content-section">
                        <div class="content-label">
                          ✨ AI Generated Output
                          <button class="copy-btn" onclick="copyToClipboard('\${uniqueId}', this)">
                            📋 Copy
                          </button>
                        </div>
                        <div id="\${uniqueId}" class="content-text content-generated">\${escapeHtml(item.generated_output)}</div>
                      </div>
                      <div class="content-meta">
                        \${item.language ? \`<span class="content-meta-item">🌍 \${item.language}</span>\` : ''}
                        \${item.account ? \`<span class="content-meta-item">👤 \${item.account}</span>\` : ''}
                      </div>
                    </div>
                  </div>
                \`;
              }).join('');

              container.innerHTML = '<div class="content-grid">' + html + '</div>';
              updatePagination(total);
            } else {
              container.innerHTML = '<div class="no-results"><p>No AI-generated content found</p></div>';
              document.getElementById('pagination').innerHTML = '';
            }
          } else {
            container.innerHTML = '<div class="no-results"><p>No content found</p></div>';
          }
        } catch (error) {
          console.error('Failed to load content:', error);
          container.innerHTML = '<div class="no-results"><p>Failed to load content</p></div>';
        }
      }

      function formatMode(mode) {
        const modeLabels = {
          'rewrite_twitter': 'Twitter',
          'rewrite_linkedin': 'LinkedIn',
          'describe_image': 'Image Desc',
          'summarize': 'Summary',
          'translate': 'Translation',
          'processed': 'Processed'
        };
        return modeLabels[mode] || mode.replace(/_/g, ' ').replace(/\\b\\w/g, l => l.toUpperCase());
      }

      function copyToClipboard(elementId, button) {
        const element = document.getElementById(elementId);
        const text = element.textContent;

        navigator.clipboard.writeText(text).then(() => {
          button.innerHTML = '✓ Copied';
          button.classList.add('copied');
          setTimeout(() => {
            button.innerHTML = '📋 Copy';
            button.classList.remove('copied');
          }, 2000);
        }).catch(err => {
          console.error('Failed to copy:', err);
        });
      }

      function updatePagination(total) {
        const totalPages = Math.ceil(total / perPage);
        const pagination = document.getElementById('pagination');

        if (totalPages <= 1) {
          pagination.innerHTML = '';
          return;
        }

        let html = '';
        html += '<button ' + (currentPage === 1 ? 'disabled' : '') + ' onclick="goToPage(' + (currentPage - 1) + ')">← Prev</button>';

        for (let i = 1; i <= totalPages; i++) {
          if (i === 1 || i === totalPages || (i >= currentPage - 2 && i <= currentPage + 2)) {
            html += '<button class="' + (i === currentPage ? 'active' : '') + '" onclick="goToPage(' + i + ')">' + i + '</button>';
          } else if (i === currentPage - 3 || i === currentPage + 3) {
            html += '<span style="padding: 0.5rem;">...</span>';
          }
        }

        html += '<button ' + (currentPage === totalPages ? 'disabled' : '') + ' onclick="goToPage(' + (currentPage + 1) + ')">Next →</button>';
        pagination.innerHTML = html;
      }

      function goToPage(page) {
        currentPage = page;
        loadContent();
        window.scrollTo({ top: 0, behavior: 'smooth' });
      }

      function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
      }

      // Event listeners
      document.getElementById('search-input').addEventListener('input', debounce(function(e) {
        currentSearch = e.target.value;
        currentPage = 1;
        loadContent();
      }, 300));

      document.getElementById('mode-filter').addEventListener('change', function(e) {
        currentMode = e.target.value;
        currentPage = 1;
        loadContent();
      });

      document.getElementById('sort-select').addEventListener('change', function(e) {
        currentSort = e.target.value;
        loadContent();
      });

      function debounce(func, wait) {
        let timeout;
        return function(...args) {
          clearTimeout(timeout);
          timeout = setTimeout(() => func.apply(this, args), wait);
        };
      }

      // Initial load
      if (${count} > 0) {
        loadContent();
      }
    </script>
  `;

  return baseLayout({
    title: 'AI Content - Universal Text Processor',
    content,
    styles,
    scripts
  });
}
